
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:38 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:38 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/msys64/mingw64/bin/cc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is GNU, found in:
        C:/SFML/SFML-2.6.1/CMakeFiles/3.29.0-rc3/CompilerIdC/a.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:38 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/msys64/mingw64/bin/c++.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.exe"
      
      The CXX compiler identification is GNU, found in:
        C:/SFML/SFML-2.6.1/CMakeFiles/3.29.0-rc3/CompilerIdCXX/a.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:64 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:38 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/SFML/SFML-2.6.1/CMakeFiles/CMakeScratch/TryCompile-205qr6"
      binary: "C:/SFML/SFML-2.6.1/CMakeFiles/CMakeScratch/TryCompile-205qr6"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_OSX_SYSROOT: ""
      CMAKE_USER_MAKE_RULES_OVERRIDE: "C:/SFML/SFML-2.6.1/cmake/CompilerOptionsOverride.cmake"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/SFML/SFML-2.6.1/CMakeFiles/CMakeScratch/TryCompile-205qr6'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~2/GnuWin32/bin/make.exe -f Makefile cmTC_ee8de/fast
        C:/PROGRA~2/GnuWin32/bin/make.exe  -f CMakeFiles/cmTC_ee8de.dir/build.make CMakeFiles/cmTC_ee8de.dir/build
        make.exe[1]: Entering directory `C:/SFML/SFML-2.6.1/CMakeFiles/CMakeScratch/TryCompile-205qr6'
        The system cannot find the path specified.
        make.exe[1]: *** [CMakeFiles/cmTC_ee8de.dir/CMakeCCompilerABI.c.obj] Error 1
        make.exe[1]: Leaving directory `C:/SFML/SFML-2.6.1/CMakeFiles/CMakeScratch/TryCompile-205qr6'
        make.exe: *** [cmTC_ee8de/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:38 (project)"
    checks:
      - "Check for working C compiler: C:/msys64/mingw64/bin/cc.exe"
    directories:
      source: "C:/SFML/SFML-2.6.1/CMakeFiles/CMakeScratch/TryCompile-5urdoz"
      binary: "C:/SFML/SFML-2.6.1/CMakeFiles/CMakeScratch/TryCompile-5urdoz"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_OSX_SYSROOT: ""
      CMAKE_USER_MAKE_RULES_OVERRIDE: "C:/SFML/SFML-2.6.1/cmake/CompilerOptionsOverride.cmake"
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: 'C:/SFML/SFML-2.6.1/CMakeFiles/CMakeScratch/TryCompile-5urdoz'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~2/GnuWin32/bin/make.exe -f Makefile cmTC_37ead/fast
        C:/PROGRA~2/GnuWin32/bin/make.exe  -f CMakeFiles/cmTC_37ead.dir/build.make CMakeFiles/cmTC_37ead.dir/build
        make.exe[1]: Entering directory `C:/SFML/SFML-2.6.1/CMakeFiles/CMakeScratch/TryCompile-5urdoz'
        The system cannot find the path specified.
        make.exe[1]: *** [CMakeFiles/cmTC_37ead.dir/testCCompiler.c.obj] Error 1
        make.exe[1]: Leaving directory `C:/SFML/SFML-2.6.1/CMakeFiles/CMakeScratch/TryCompile-5urdoz'
        make.exe: *** [cmTC_37ead/fast] Error 2
        
      exitCode: 2
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:38 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/msys64/mingw64/bin/cc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is GNU, found in:
        C:/SFML/SFML-2.6.1/CMakeFiles/3.29.0-rc3/CompilerIdC/a.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:38 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/msys64/mingw64/bin/c++.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.exe"
      
      The CXX compiler identification is GNU, found in:
        C:/SFML/SFML-2.6.1/CMakeFiles/3.29.0-rc3/CompilerIdCXX/a.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:64 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:38 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/SFML/SFML-2.6.1/CMakeFiles/CMakeScratch/TryCompile-vpdytw"
      binary: "C:/SFML/SFML-2.6.1/CMakeFiles/CMakeScratch/TryCompile-vpdytw"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_OSX_SYSROOT: ""
      CMAKE_USER_MAKE_RULES_OVERRIDE: "C:/SFML/SFML-2.6.1/cmake/CompilerOptionsOverride.cmake"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/SFML/SFML-2.6.1/CMakeFiles/CMakeScratch/TryCompile-vpdytw'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~2/GnuWin32/bin/make.exe -f Makefile cmTC_af72e/fast
        C:/PROGRA~2/GnuWin32/bin/make.exe  -f CMakeFiles/cmTC_af72e.dir/build.make CMakeFiles/cmTC_af72e.dir/build
        make.exe[1]: Entering directory `C:/SFML/SFML-2.6.1/CMakeFiles/CMakeScratch/TryCompile-vpdytw'
        The system cannot find the path specified.
        make.exe[1]: *** [CMakeFiles/cmTC_af72e.dir/CMakeCCompilerABI.c.obj] Error 1
        make.exe[1]: Leaving directory `C:/SFML/SFML-2.6.1/CMakeFiles/CMakeScratch/TryCompile-vpdytw'
        make.exe: *** [cmTC_af72e/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:38 (project)"
    checks:
      - "Check for working C compiler: C:/msys64/mingw64/bin/cc.exe"
    directories:
      source: "C:/SFML/SFML-2.6.1/CMakeFiles/CMakeScratch/TryCompile-huvuv0"
      binary: "C:/SFML/SFML-2.6.1/CMakeFiles/CMakeScratch/TryCompile-huvuv0"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_OSX_SYSROOT: ""
      CMAKE_USER_MAKE_RULES_OVERRIDE: "C:/SFML/SFML-2.6.1/cmake/CompilerOptionsOverride.cmake"
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: 'C:/SFML/SFML-2.6.1/CMakeFiles/CMakeScratch/TryCompile-huvuv0'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~2/GnuWin32/bin/make.exe -f Makefile cmTC_af56a/fast
        C:/PROGRA~2/GnuWin32/bin/make.exe  -f CMakeFiles/cmTC_af56a.dir/build.make CMakeFiles/cmTC_af56a.dir/build
        make.exe[1]: Entering directory `C:/SFML/SFML-2.6.1/CMakeFiles/CMakeScratch/TryCompile-huvuv0'
        The system cannot find the path specified.
        make.exe[1]: *** [CMakeFiles/cmTC_af56a.dir/testCCompiler.c.obj] Error 1
        make.exe[1]: Leaving directory `C:/SFML/SFML-2.6.1/CMakeFiles/CMakeScratch/TryCompile-huvuv0'
        make.exe: *** [cmTC_af56a/fast] Error 2
        
      exitCode: 2
...
