
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/msys64/mingw64/bin/cc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is GNU, found in:
        C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/3.29.0-rc3/CompilerIdC/a.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/msys64/mingw64/bin/c++.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.exe"
      
      The CXX compiler identification is GNU, found in:
        C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/3.29.0-rc3/CompilerIdCXX/a.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:64 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-v5ma4y"
      binary: "C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-v5ma4y"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-v5ma4y'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~2/GnuWin32/bin/make.exe -f Makefile cmTC_14bf2/fast
        C:/PROGRA~2/GnuWin32/bin/make.exe  -f CMakeFiles/cmTC_14bf2.dir/build.make CMakeFiles/cmTC_14bf2.dir/build
        make.exe[1]: Entering directory `C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-v5ma4y'
        The system cannot find the path specified.
        make.exe[1]: *** [CMakeFiles/cmTC_14bf2.dir/CMakeCCompilerABI.c.obj] Error 1
        make.exe[1]: Leaving directory `C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-v5ma4y'
        make.exe: *** [cmTC_14bf2/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt"
    checks:
      - "Check for working C compiler: C:/msys64/mingw64/bin/cc.exe"
    directories:
      source: "C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-emmafl"
      binary: "C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-emmafl"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-emmafl'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~2/GnuWin32/bin/make.exe -f Makefile cmTC_f1469/fast
        C:/PROGRA~2/GnuWin32/bin/make.exe  -f CMakeFiles/cmTC_f1469.dir/build.make CMakeFiles/cmTC_f1469.dir/build
        make.exe[1]: Entering directory `C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-emmafl'
        The system cannot find the path specified.
        make.exe[1]: *** [CMakeFiles/cmTC_f1469.dir/testCCompiler.c.obj] Error 1
        make.exe[1]: Leaving directory `C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-emmafl'
        make.exe: *** [cmTC_f1469/fast] Error 2
        
      exitCode: 2
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/msys64/mingw64/bin/cc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is GNU, found in:
        C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/3.29.0-rc3/CompilerIdC/a.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/msys64/mingw64/bin/c++.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.exe"
      
      The CXX compiler identification is GNU, found in:
        C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/3.29.0-rc3/CompilerIdCXX/a.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:64 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-e9z6on"
      binary: "C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-e9z6on"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-e9z6on'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~2/GnuWin32/bin/make.exe -f Makefile cmTC_159f9/fast
        C:/PROGRA~2/GnuWin32/bin/make.exe  -f CMakeFiles/cmTC_159f9.dir/build.make CMakeFiles/cmTC_159f9.dir/build
        make.exe[1]: Entering directory `C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-e9z6on'
        The system cannot find the path specified.
        make.exe[1]: *** [CMakeFiles/cmTC_159f9.dir/CMakeCCompilerABI.c.obj] Error 1
        make.exe[1]: Leaving directory `C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-e9z6on'
        make.exe: *** [cmTC_159f9/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt"
    checks:
      - "Check for working C compiler: C:/msys64/mingw64/bin/cc.exe"
    directories:
      source: "C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-19xc2u"
      binary: "C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-19xc2u"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-19xc2u'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~2/GnuWin32/bin/make.exe -f Makefile cmTC_92655/fast
        C:/PROGRA~2/GnuWin32/bin/make.exe  -f CMakeFiles/cmTC_92655.dir/build.make CMakeFiles/cmTC_92655.dir/build
        make.exe[1]: Entering directory `C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-19xc2u'
        The system cannot find the path specified.
        make.exe[1]: *** [CMakeFiles/cmTC_92655.dir/testCCompiler.c.obj] Error 1
        make.exe[1]: Leaving directory `C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-19xc2u'
        make.exe: *** [cmTC_92655/fast] Error 2
        
      exitCode: 2
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/msys64/mingw64/bin/cc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is GNU, found in:
        C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/3.29.0-rc3/CompilerIdC/a.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/msys64/mingw64/bin/c++.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.exe"
      
      The CXX compiler identification is GNU, found in:
        C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/3.29.0-rc3/CompilerIdCXX/a.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:64 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-aafedw"
      binary: "C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-aafedw"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-aafedw'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~2/GnuWin32/bin/make.exe -f Makefile cmTC_df42f/fast
        C:/PROGRA~2/GnuWin32/bin/make.exe  -f CMakeFiles/cmTC_df42f.dir/build.make CMakeFiles/cmTC_df42f.dir/build
        make.exe[1]: Entering directory `C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-aafedw'
        The system cannot find the path specified.
        make.exe[1]: *** [CMakeFiles/cmTC_df42f.dir/CMakeCCompilerABI.c.obj] Error 1
        make.exe[1]: Leaving directory `C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-aafedw'
        make.exe: *** [cmTC_df42f/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt"
    checks:
      - "Check for working C compiler: C:/msys64/mingw64/bin/cc.exe"
    directories:
      source: "C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-45an9t"
      binary: "C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-45an9t"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-45an9t'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~2/GnuWin32/bin/make.exe -f Makefile cmTC_9c9fe/fast
        C:/PROGRA~2/GnuWin32/bin/make.exe  -f CMakeFiles/cmTC_9c9fe.dir/build.make CMakeFiles/cmTC_9c9fe.dir/build
        make.exe[1]: Entering directory `C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-45an9t'
        The system cannot find the path specified.
        make.exe[1]: *** [CMakeFiles/cmTC_9c9fe.dir/testCCompiler.c.obj] Error 1
        make.exe[1]: Leaving directory `C:/Users/Peyton/source/repos/FortIDE/CMakeFiles/CMakeScratch/TryCompile-45an9t'
        make.exe: *** [cmTC_9c9fe/fast] Error 2
        
      exitCode: 2
...
